services:
  webrtc_bridge:
    image: phntm/webrtc-bridge-dev:humble
    container_name: webrtc-bridge-dev
    hostname: webrtc-bridge
    restart: unless-stopped
    privileged: true
    network_mode: host
    # ports:
    # - 51688:51688
    volumes:
      - ~/phntm_webrtc_bridge:/ros2_ws/src/webrtc_bridge
      - ~/aioice:/ros2_ws/src/aioice
      - ~/aiortc:/ros2_ws/src/aiortc
      - ~/phntm_webrtc_bridge_launch_params.yaml:/ros2_ws/webrtc_bridge_params.yaml
    devices:
      - /dev:/dev
    command:
      # ros2 launch phntm_webrtc_bridge bridge_launch.py
      /bin/sh -c "while sleep 1000; do :; done"

